[package]
name = "fiber-sphinx"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.28.0", features = ["serde"] }
sha2 = "0.10.8"
hmac = "0.12.1"
thiserror = "1.0"

[dev-dependencies]
hex-literal = "0.4.1"
base16 = "0.2.1"
